/* Generated By:JavaCC: Do not edit this line. Parser2Constants.java */
package org.consoli.javaccgwt.example2.parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Parser2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int FOUR = 2;
  /** RegularExpression Id. */
  int FIVE = 3;
  /** RegularExpression Id. */
  int SIX = 4;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "\"four\"",
    "\"five\"",
    "\"six\"",
  };

}
