/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package org.consoli.javaccgwt.example1.parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int ONE = 2;
  /** RegularExpression Id. */
  int TWO = 3;
  /** RegularExpression Id. */
  int THREE = 4;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "\"one\"",
    "\"two\"",
    "\"three\"",
  };

}
